/// Flutter icons CopticMeetIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CopticMeetIcons
///      fonts:
///       - asset: fonts/CopticMeetIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CopticMeetIcons {
  CopticMeetIcons._();

  static const _kFontFam = 'CopticMeetIcons';
  static const _kFontPkg = null;

  static const IconData left_coptic_meet = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData right_coptic_meet = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData super_like_coptic_meet = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData send_coptic_meet = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData education_institution_coptic_meet = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData education_level_coptic_meet = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData height_coptic_meet = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location_2 = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData undo_back_ = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star_sign = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData kids_filter = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pets_filter = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
